### ISSUE TITLE
rq.group.fit doesn't pass the parameters for SCAD or MCP to solvers

### ISSUE THREAD

**Issue by ericdunipace** [bssherwood/rqpen#1]
Looking at the code, I noticed that the `rq.group.fit` calls the `QICD.group` function but doesn't pass the relevant `a` parameter for the SCAD or MCP penalties.

The default arguments to the`rq.group.fit` function are 
`(x, y, groups, tau = 0.5, lambda, intercept = TRUE, 
    penalty = "LASSO", alg = "QICD", a = 3.7, penGroups = NULL, 
    ...) `
but the QICD.group function is called like this in the function
`coefs <- QICD.group(y, x, groups, tau, lambda, intercept, 
      penalty, ...)`
which won't pass the `a` parameter since it isn't in the dots. A suggested fix would be
`coefs <- QICD.group(y, x, groups, tau, lambda, intercept, 
      penalty, a = a, ...)`.

I believe the same is true with the `rq.group.lin.prog` function also in rq.group.fit:
`return_val <- rq.group.lin.prog(x, y, groups, tau, 
        lambda, intercept = intercept, penalty = penalty, 
        penGroups = penGroups, ...)`
should be 
`return_val <- rq.group.lin.prog(x, y, groups, tau, 
        lambda, intercept = intercept, penalty = penalty, 
        penGroups = penGroups, a = a, ...)`

Happy to make a pull request if that's easier.

I also have a question about the group penalty for the regular lasso, but will ask in a separate post.

**Comment by bssherwood** [comment]
Thank you for noticing this. The function rq.group.fit has been updated with your suggested changes. Will submit to CRAN ASAP.
