### ISSUE TITLE
Group lasso function doesn't give group penalty?

### ISSUE THREAD

**Issue by ericdunipace** [bssherwood/rqpen#2]
I also noticed that the `rq.group.fit` function with the lasso penalty doesn't appear to do the group lasso, but just a regular lasso. I ran the comparison in the text file attached.

It looks like the group and non-group code produces the same coefficients. I believe this isn't the expected output but maybe I've missed something

[group_lasso_check.txt](https://github.com/bssherwood/rqpen/files/4447895/group_lasso_check.txt)

**Comment by bssherwood** [comment]
The group penalties use the l1 norm instead of the l2 norm as stated in the help file for rq.group.fit. Thus you are correct that the regular lasso returns the same result as the group lasso. Will add a warning about this.
