### ISSUE TITLE
Interpret the cross validation by rq.pen.cv()

### ISSUE THREAD

**Issue by Steviey** [bssherwood/rqpen#5]
Hello Mr. Sherwood

I want to find and use the best lambda after cv, for the next fit.
But where can I find the best lambda?
Is it in the btr-table and which column?
And what is the meaning of col 'minCv'?
Is 'lambda-search' via cv integrated in rq.pen()?
And which params of rq.pen() are most interesting for a custom grid-search?
Thank you very much.
```
myY   <- df_train$y
myX   <- stats::model.matrix(myFormula, df_train)[,-1]
cv2   <- rq.pen.cv(myX,myY,tau=seq(0.1, 0.9, by = 0.1),nfolds=10,nlambda=100)

print(as_tibble(cv2$btr),n=100,max_extra_cols=0,width=110)

A tibble: 9 × 11
    tau minCv  lambda lambdaIndex lambda1se lambda1seIndex     a   cvse modelsIndex nonzero  nzse
  <dbl> <dbl>   <dbl>       <int>     <dbl>          <int> <dbl>  <dbl>       <int>   <int> <int>
1   0.1  1.32 0.00380         100    0.0388             50     1 0.0342           1       3     4
2   0.2  2.15 0.00380         100    0.0514             44     1 0.0549           2       3     2
3   0.3  2.62 0.00380         100    0.0538             43     1 0.0584           3       3     3
4   0.4  2.87 0.00380         100    0.0538             43     1 0.0571           4       3     3
5   0.5  2.92 0.00380         100    0.0538             43     1 0.0610           5       3     3
6   0.6  2.85 0.00380         100    0.0490             45     1 0.0524           6       3     2
7   0.7  2.56 0.00417          98    0.0447             47     1 0.0429           7       2     2
8   0.8  2.06 0.00380         100    0.0354             52     1 0.0296           8       3     2
9   0.9  1.26 0.00380         100    0.0233             61     1 0.0143           9       3     3
```

**Comment by bssherwood** [comment]
1. Best Lambda: that is lambda or lambda1se depending on which rule you want to use, the smallest cv error or sparsest model within 1se of the smallest. 
2. I think i've answered this question.
3. minCv is the value of the minimum cross validation error for that given value of tau. 
4. No, you need to use rq.pen.cv()
5. a and lambda, and the value a is only used for non-lasso, non-ridge penalties.

**Comment by Steviey** [comment]
Thank you for the answer.
So could we then say, that the following code is right, to get the best lambda from rq.pen.cv()?

```
myY     <- df_train$y
myX     <- stats::model.matrix(myFormula, df_train)[,-1]
cv2     <- rq.pen.cv(myX,myY,tau=alpha,nfolds=10,nlambda=6000)

bestParams          <- cv2$btr %>% dplyr::arrange(minCv)
bestParamsLambda    <- bestParams[['lambda']][1]
bestParamsLambda1Se <- bestParams[['lambda1se']][1]

View(bestParams)
View(bestParamsLambda)
View(bestParamsLambda1Se)
stop()

```
Thank you...
...And by the way, what are the main model assumptions of rqPen? 
Is there a 'general rule' for preprocessing input in regard to rqPen?
Are there any other documentations available.

**Comment by bssherwood** [comment]
Sorry for the late response, yes that looks correct to me. By default the predictors are scaled to have mean zero and standard deviation one but the coefficients are then returned on the original x scale. Regarding the model assumptions you are fitting a quantile regression model with a penalty. I recommend the following two papers if you are not familiar with quantile regression

http://www.econ.uiuc.edu/~roger/research/intro/rq3.pdf
https://esajournals.onlinelibrary.wiley.com/doi/10.1890/1540-9295%282003%29001%5B0412%3AAGITQR%5D2.0.CO%3B2

Below is a good introduction to penalized methods,

https://glmnet.stanford.edu/articles/glmnet.html

I also have a work in progress vignette for rqPen

https://github.com/bssherwood/rqpen/blob/master/ignore/rqPenArticle.pdf
