### ISSUE TITLE
rqPen parameters

### ISSUE THREAD

**Issue by Steviey** [bssherwood/rqpen#6]
Doing a 'custom' grid search, which parameter spaces would be worth to test in regard to the entries in column 'penalty'? Which additional columns in the search grid would make sense?

![image](https://user-images.githubusercontent.com/3146082/214783023-5bf84bc0-6ef6-42ec-9830-84dde5fc9e77.png)

**Comment by bssherwood** [comment]
Again, sorry for the late response but for some reason I did not see these comments. I do not understand the question. Generally speaking I usually do a cross-validation or train/test split if I want to determine the best approach.
